import requests
import json

# Replace with your GitHub Personal Access Token (PAT) and the GraphQL query.
GITHUB_ACCESS_TOKEN = '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'
GITHUB_GRAPHQL_QUERY = '''
{
  repository(owner: "susrk", name: "GitHub-Actions-Queue") {
    actions {
      workflow_runs(first: 100, status: QUEUED) {
        totalCount
      }
    }
  }
}
'''

# Define the GraphQL API endpoint.
GITHUB_API_ENDPOINT = 'https://api.github.com/graphql'

# Create the headers with the PAT for authentication.
headers = {
    'Authorization': f'token {GITHUB_ACCESS_TOKEN}',
}

# Create a JSON request payload with the GraphQL query.
payload = {
    'query': GITHUB_GRAPHQL_QUERY,
}

# Make the GraphQL API request.
response = requests.post(GITHUB_API_ENDPOINT, headers=headers, json=payload)

# Check the response status code.
if response.status_code == 200:
    data = response.json()
    queue_status = data.get('data', {}).get('repository', {}).get('actions', {}).get('workflow_runs', {}).get('totalCount')
    print(f'Queue status: {queue_status}')
else:
    print(f'Failed to fetch queue status. Status code: {response.status_code}')

