name: Parallel Job Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_job_1:
    name: Deploy Job 1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update Status
        run: |
          ACCESS_TOKEN="${{ secrets.ACCESS }}"
          WORKFLOW_ID="${{ github.run_id }}"
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.repository }}"
          
          GRAPHQL_API_URL="https://api.github.com/graphql"
          
          curl -X POST -H "Authorization: bearer $ACCESS_TOKEN" -d \
            "{
              \"query\": \"mutation {
                updateSubscription(input: {clientMutationId: \\\"1\\\", state: \"IN_PROGRESS\"}) {
                  clientMutationId
                }
              }\"
            }" $GRAPHQL_API_URL

      - name: Deploy Job 1 Step
        run: |
          # Add your deployment steps for Job 1 here
          echo "Deploying Job 1"
          

  deploy_job_2:
    name: Deploy Job 2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Job 2 Step
        run: |
          # Add your deployment steps for Job 2 here
          echo "Deploying Job 2"
          sleep 2m 

  deploy_job_3:
    name: Deploy Job 3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Job 3 Step
        run: |
          # Add your deployment steps for Job 3 here
          echo "Deploying Job 3"
          sleep 2m 
